import React from 'react';
import './Home.css'

const Home = () => {
    return (
        <section>
            <div className='article'>
                <h2>This is real home</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque dignissimos odit dolorem eaque porro aperiam harum libero repellendus laudantium voluptas, mollitia, ipsam aut, blanditiis unde magni! Reprehenderit laudantium magnam necessitatibus earum optio est quam repellendus expedita debitis vitae fugiat laboriosam neque architecto dolor quaerat nam animi eum sit ipsum nulla, deleniti quasi quae. Nesciunt quas at officia? In dolorem quos perferendis molestias saepe quis reiciendis libero eveniet, ullam cum, consequuntur unde nemo minima voluptates officia temporibus beatae impedit deserunt illum dolor, quam nihil vitae iusto? Expedita commodi natus veritatis quas vitae incidunt tempora unde corrupti ducimus, officiis animi voluptatem possimus. Voluptatibus accusamus placeat maiores amet veniam dolorum, quo rerum iste magni beatae! Ad voluptas mollitia velit dolor reiciendis quo nobis itaque illo expedita? Temporibus pariatur ut iusto fugiat. Et a debitis laudantium corporis, facilis atque fugiat error nemo ducimus dolorem perspiciatis illo! Corrupti vitae ex illum ipsa placeat id tempora, quia unde. Rerum maxime quaerat nisi nemo nam ut similique illum tempore explicabo adipisci suscipit eveniet asperiores culpa dignissimos provident reiciendis veritatis unde, mollitia odio. Quasi ex itaque cumque mollitia quos hic perferendis temporibus eligendi eaque atque voluptatum laboriosam quae, sunt rem culpa repudiandae ut nihil, deserunt quam. Doloremque mollitia temporibus tempore optio cupiditate perspiciatis ad error consequuntur fuga autem, nobis id nulla voluptatibus, provident velit repellat eos animi assumenda? In distinctio assumenda illo corporis necessitatibus esse beatae voluptates laboriosam quaerat atque? Cum maxime reprehenderit accusamus sequi alias numquam corrupti! Eum, molestias! Quasi tempore error hic voluptatibus quae consequuntur, laudantium veniam, excepturi expedita pariatur provident rerum. Perferendis rerum enim fuga qui aspernatur ducimus totam vitae itaque, natus maxime sit pariatur aut corrupti ex a temporibus ab? Esse nihil velit ab soluta voluptatum aliquam, illo nesciunt, excepturi tenetur quo corrupti praesentium dolorem culpa voluptatibus sunt perferendis molestias eveniet repellat voluptatem. Ex?</p>
            </div>
            <div className='article'>
                <h2>This is real home</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque dignissimos odit dolorem eaque porro aperiam harum libero repellendus laudantium voluptas, mollitia, ipsam aut, blanditiis unde magni! Reprehenderit laudantium magnam necessitatibus earum optio est quam repellendus expedita debitis vitae fugiat laboriosam neque architecto dolor quaerat nam animi eum sit ipsum nulla, deleniti quasi quae. Nesciunt quas at officia? In dolorem quos perferendis molestias saepe quis reiciendis libero eveniet, ullam cum, consequuntur unde nemo minima voluptates officia temporibus beatae impedit deserunt illum dolor, quam nihil vitae iusto? Expedita commodi natus veritatis quas vitae incidunt tempora unde corrupti ducimus, officiis animi voluptatem possimus. Voluptatibus accusamus placeat maiores amet veniam dolorum, quo rerum iste magni beatae! Ad voluptas mollitia velit dolor reiciendis quo nobis itaque illo expedita? Temporibus pariatur ut iusto fugiat. Et a debitis laudantium corporis, facilis atque fugiat error nemo ducimus dolorem perspiciatis illo! Corrupti vitae ex illum ipsa placeat id tempora, quia unde. Rerum maxime quaerat nisi nemo nam ut similique illum tempore explicabo adipisci suscipit eveniet asperiores culpa dignissimos provident reiciendis veritatis unde, mollitia odio. Quasi ex itaque cumque mollitia quos hic perferendis temporibus eligendi eaque atque voluptatum laboriosam quae, sunt rem culpa repudiandae ut nihil, deserunt quam. Doloremque mollitia temporibus tempore optio cupiditate perspiciatis ad error consequuntur fuga autem, nobis id nulla voluptatibus, provident velit repellat eos animi assumenda? In distinctio assumenda illo corporis necessitatibus esse beatae voluptates laboriosam quaerat atque? Cum maxime reprehenderit accusamus sequi alias numquam corrupti! Eum, molestias! Quasi tempore error hic voluptatibus quae consequuntur, laudantium veniam, excepturi expedita pariatur provident rerum. Perferendis rerum enim fuga qui aspernatur ducimus totam vitae itaque, natus maxime sit pariatur aut corrupti ex a temporibus ab? Esse nihil velit ab soluta voluptatum aliquam, illo nesciunt, excepturi tenetur quo corrupti praesentium dolorem culpa voluptatibus sunt perferendis molestias eveniet repellat voluptatem. Ex?</p>
            </div>
            <div className='article'>
                <h2>This is real home</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque dignissimos odit dolorem eaque porro aperiam harum libero repellendus laudantium voluptas, mollitia, ipsam aut, blanditiis unde magni! Reprehenderit laudantium magnam necessitatibus earum optio est quam repellendus expedita debitis vitae fugiat laboriosam neque architecto dolor quaerat nam animi eum sit ipsum nulla, deleniti quasi quae. Nesciunt quas at officia? In dolorem quos perferendis molestias saepe quis reiciendis libero eveniet, ullam cum, consequuntur unde nemo minima voluptates officia temporibus beatae impedit deserunt illum dolor, quam nihil vitae iusto? Expedita commodi natus veritatis quas vitae incidunt tempora unde corrupti ducimus, officiis animi voluptatem possimus. Voluptatibus accusamus placeat maiores amet veniam dolorum, quo rerum iste magni beatae! Ad voluptas mollitia velit dolor reiciendis quo nobis itaque illo expedita? Temporibus pariatur ut iusto fugiat. Et a debitis laudantium corporis, facilis atque fugiat error nemo ducimus dolorem perspiciatis illo! Corrupti vitae ex illum ipsa placeat id tempora, quia unde. Rerum maxime quaerat nisi nemo nam ut similique illum tempore explicabo adipisci suscipit eveniet asperiores culpa dignissimos provident reiciendis veritatis unde, mollitia odio. Quasi ex itaque cumque mollitia quos hic perferendis temporibus eligendi eaque atque voluptatum laboriosam quae, sunt rem culpa repudiandae ut nihil, deserunt quam. Doloremque mollitia temporibus tempore optio cupiditate perspiciatis ad error consequuntur fuga autem, nobis id nulla voluptatibus, provident velit repellat eos animi assumenda? In distinctio assumenda illo corporis necessitatibus esse beatae voluptates laboriosam quaerat atque? Cum maxime reprehenderit accusamus sequi alias numquam corrupti! Eum, molestias! Quasi tempore error hic voluptatibus quae consequuntur, laudantium veniam, excepturi expedita pariatur provident rerum. Perferendis rerum enim fuga qui aspernatur ducimus totam vitae itaque, natus maxime sit pariatur aut corrupti ex a temporibus ab? Esse nihil velit ab soluta voluptatum aliquam, illo nesciunt, excepturi tenetur quo corrupti praesentium dolorem culpa voluptatibus sunt perferendis molestias eveniet repellat voluptatem. Ex?</p>
            </div>
        </section>
    );
};

export default Home;